// Package event models Palladium's Event domain: the immutable
// operational history described in docs/02-DESIGN-PRINCIPLES.md,
// principle 10 ("Events as Operational History"). An Event records that
// something has already happened — it carries no business logic and is
// never updated or deleted once written.
//
// EntityType/EntityID identify what the event is about (e.g.
// entity_type="service") rather than a typed reference to any specific
// domain package, so this package has no dependency on customer,
// service, or any other domain — any part of the system can record an
// event about any entity without this package growing a new field or
// import for it.
package event

import (
	"time"

	"github.com/google/uuid"
)

// Event is a single, immutable fact about something that happened to an
// entity elsewhere in the system.
type Event struct {
	ID         uuid.UUID
	EntityType string
	EntityID   uuid.UUID
	Type       string
	Message    string
	Metadata   map[string]any

	// ActorUserID is nil for events generated by the system itself (e.g.
	// a workflow transition with no human operator behind it) rather
	// than a specific user action.
	ActorUserID *uuid.UUID

	CreatedAt time.Time
}
