<script setup lang="ts">
import { computed, useTemplateRef } from 'vue'
import BaseIcon from '@/components/base/BaseIcon.vue'
import { useDetailWorkspaceContext } from '@/composables/useDetailWorkspace'
import { useDisclosure } from '@/composables/useDisclosure'

/**
 * Auto-generated by DetailWorkspace -- never written directly by a
 * consumer (docs/09-WORKSPACE-SPECIFICATIONS.md, "Contents Navigation":
 * "The navigation should automatically discover every rendered
 * SectionCard. No duplicate configuration should be required"). It reads
 * the same provide/inject context DetailWorkspace populates, so it has
 * nothing to configure and no notion of business objects.
 *
 * Two renderings switched by CSS media query only (no JS viewport
 * detection, matching AppSidebar/TopNavigation's existing pattern): a
 * sticky vertical list on desktop, and a compact disclosure dropdown on
 * mobile so an always-open list doesn't consume scarce vertical space.
 */
const registry = useDetailWorkspaceContext()
const { sections, activeSectionId, goToSection } = registry

const rootEl = useTemplateRef<HTMLElement>('root')
const { open, toggle, close } = useDisclosure(rootEl)

const activeSection = computed(() =>
  sections.value.find((section) => section.id === activeSectionId.value),
)

function select(id: string) {
  goToSection(id)
  close()
}
</script>

<template>
  <nav v-if="sections.length > 0" class="contents-navigation" aria-label="Sections">
    <ul class="contents-navigation__list contents-navigation__list--desktop">
      <li v-for="section in sections" :key="section.id">
        <a
          :href="`#${section.id}`"
          class="contents-navigation__link"
          :class="{ 'contents-navigation__link--active': section.id === activeSectionId }"
          :aria-current="section.id === activeSectionId ? 'true' : undefined"
          @click.prevent="select(section.id)"
        >
          <BaseIcon v-if="section.icon" :name="section.icon" size="sm" />
          <span>{{ section.title }}</span>
        </a>
      </li>
    </ul>

    <div ref="root" class="contents-navigation__mobile">
      <button
        type="button"
        class="contents-navigation__trigger"
        :aria-expanded="open"
        aria-controls="contents-navigation-mobile-list"
        @click="toggle"
      >
        <span>{{ activeSection?.title ?? 'Sections' }}</span>
        <BaseIcon
          name="chevron-down"
          size="sm"
          class="contents-navigation__trigger-icon"
          :class="{ 'contents-navigation__trigger-icon--open': open }"
        />
      </button>
      <ul
        v-if="open"
        id="contents-navigation-mobile-list"
        class="contents-navigation__list contents-navigation__list--mobile"
      >
        <li v-for="section in sections" :key="section.id">
          <a
            :href="`#${section.id}`"
            class="contents-navigation__link"
            :class="{ 'contents-navigation__link--active': section.id === activeSectionId }"
            :aria-current="section.id === activeSectionId ? 'true' : undefined"
            @click.prevent="select(section.id)"
          >
            <BaseIcon v-if="section.icon" :name="section.icon" size="sm" />
            <span>{{ section.title }}</span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</template>

<style scoped>
.contents-navigation {
  flex-shrink: 0;
}

.contents-navigation__list--desktop {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
  width: 200px;
  position: sticky;
  top: var(--space-5);
}

.contents-navigation__mobile {
  display: none;
}

.contents-navigation__link {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-3);
  border-radius: var(--radius-sm);
  border-left: 2px solid transparent;
  color: var(--color-text-secondary);
  text-decoration: none;
  font-size: var(--font-size-sm);
}

.contents-navigation__link:hover {
  color: var(--color-text-primary);
  background-color: var(--color-bg);
}

.contents-navigation__link--active {
  color: var(--color-brand);
  border-left-color: var(--color-brand);
  background-color: var(--color-info-bg);
  font-weight: var(--font-weight-medium);
}

@media (max-width: 960px) {
  .contents-navigation__list--desktop {
    display: none;
  }

  .contents-navigation__mobile {
    display: block;
    position: sticky;
    top: 0;
    z-index: 10;
    background-color: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
  }

  .contents-navigation__trigger {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    padding: var(--space-3) var(--space-4);
    border: none;
    background: transparent;
    font: inherit;
    font-weight: var(--font-weight-medium);
    color: var(--color-text-primary);
    cursor: pointer;
  }

  .contents-navigation__trigger-icon {
    transition: transform var(--motion-normal) var(--motion-ease);
  }

  .contents-navigation__trigger-icon--open {
    transform: rotate(180deg);
  }

  .contents-navigation__list--mobile {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
    padding: var(--space-2);
    border-top: 1px solid var(--color-border);
  }
}

@media (prefers-reduced-motion: reduce) {
  .contents-navigation__trigger-icon {
    transition: none;
  }
}
</style>
